version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    command: yarn start